# Generated by Django 4.2.27 on 2026-01-20 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interest_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='loan',
            name='given_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
