# Generated by Django 4.2.27 on 2026-01-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interest_app', '0002_loan_created_at_loan_given_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='interest_rate',
            new_name='monthly_interest_percent',
        ),
    ]
