# Generated by Django 4.2.27 on 2026-04-10 06:36

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interest_app', '0003_rename_interest_rate_loan_monthly_interest_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('daily_interest_rate', models.DecimalField(decimal_places=3, default=Decimal('1.5'), max_digits=7)),
                ('number_of_days', models.PositiveIntegerField(default=1)),
                ('given_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
